#:mute

    #:set LIST_OPERATOR = ['add', 'div', 'mul', 'sub']

#:endmute
module binary_operator_checker

    use, intrinsic :: ieee_arithmetic, only: ieee_quiet_nan, ieee_value



    use, non_intrinsic :: eml_type_fortran

    use, non_intrinsic :: ieee_class_fortran

    use, non_intrinsic :: operator_checker




    implicit none



    private

    public :: real64

    public :: binary_operator_checker_type

#:for OPERATOR in LIST_OPERATOR
    public :: check_binary_${OPERATOR}$
#:endfor



    type, extends(operator_checker_class) :: binary_operator_checker_type

        real(real64) :: r_y

        type(eml_real64_type) :: e_y

        contains

        procedure, pass :: display
        procedure, pass :: initialize

    end type



    interface
    #:for OPERATOR in LIST_OPERATOR

        module subroutine check_binary_${OPERATOR}$
        end subroutine
    #:endfor

    end interface



    contains



    subroutine display(self, operation)

        class(binary_operator_checker_type), intent(in) :: self

        character(*), intent(in) :: operation



        character(:), allocatable :: offset



        offset = repeat( ' ', len(operation) )
        
        print *
        print *,      self%r_x  , '; ', offset, '  x                @ real64'
        print *,      self%r_y  , '; ', offset, '         y         @ real64'
        print *, real(self%e_x) , '; ', offset, '  x%re             @ eml'
        print *, imag(self%e_x) , '; ', offset, '  x%im             @ eml'
        print *, real(self%e_y) , '; ', offset, '         y%re      @ eml'
        print *, imag(self%e_y) , '; ', offset, '         y%im      @ eml'

        print *,      self%r_op  , '; ', operation, '( x    , y    )    @ real64'
        print *, real(self%e_op) , '; ', operation, '( x    , y    )%re @ eml'
        print *, imag(self%e_op) , '; ', operation, '( x    , y    )%im @ eml'

        call self%display_error_binary(operation)

    end subroutine



    elemental subroutine initialize(self)

        class(binary_operator_checker_type), intent(inout) :: self

        associate( nan => ieee_value(0.0_real64, ieee_quiet_nan) )

            self%r_x  = nan
            self%r_op = nan

            self%e_x  = nan
            self%e_op = nan

        end associate

        call self%initialize_error

    end subroutine initialize

end module
