#:mute

    #:if defined('WITH_ADD')
        #:set OPERATION = 'add'
    #:endif

    #:if defined('WITH_AVG')
        #:set OPERATION = 'avg'
    #:endif

    #:if defined('WITH_DIV')
        #:set OPERATION = 'div'
    #:endif

    #:if defined('WITH_HYPOT')
        #:set OPERATION = 'hypot'
    #:endif

    #:if defined('WITH_MUL')
        #:set OPERATION = 'mul'
    #:endif

    #:if defined('WITH_POW')
        #:set OPERATION = 'pow'
    #:endif

    #:if defined('WITH_SUB')
        #:set OPERATION = 'sub'
    #:endif

    #:set I_MAX =   16
    #:set I_MIN = - I_MAX
    #:set J_MAX =   I_MAX
    #:set J_MIN =   I_MIN
    #:set STEP  =   0.5

    #:set PROGRAM_NAME = 'check_binary_' + OPERATION

    #:set DATA_FILE_NAME = PROGRAM_NAME + '.dat'

#:endmute
