#:include 'check_binary_common.fypp'
submodule (binary_operator_checker) imp_${PROGRAM_NAME}$
    !! [SymbolicRegressionPackage/EML_toolkit/EmL_compiler/Test_C_math_h/run_binary_suite_c.py at master · VA00/SymbolicRegressionPackage](https://github.com/VA00/SymbolicRegressionPackage/blob/master/EML_toolkit/EmL_compiler/Test_C_math_h/run_binary_suite_c.py)

    implicit none

    contains

    module procedure ${PROGRAM_NAME}$

        logical :: flag

        integer :: i, j, file_unit

        type(binary_operator_checker_type) :: record, trial



        open( &!
            newunit = file_unit , &!
            file    = 'test/${DATA_FILE_NAME}$' , &!
            status  = 'replace' &!
        )



        flag = .false.

        call record%initialize



        do i = ${I_MIN}$, ${I_MAX}$
        do j = ${J_MIN}$, ${J_MAX}$

            call trial%initialize

            trial%r_x  = ${STEP}$_real64 * i
            trial%e_x  = trial%r_x

            trial%r_y  = ${STEP}$_real64 * j
            trial%e_y  = trial%r_y

        #:if defined('WITH_SUB')
            trial%r_op = trial%r_x - trial%r_y
            trial%e_op = trial%e_x - trial%e_y
        #:endif



            if ( ieee_is_nan(trial%e_op) ) then

                call trial%display('${OPERATION}$')

                error stop ': ${OPERATION}$(x) @ eml is NaN.'

            end if



            call trial%eval_error



            write(file_unit, *) &!
            &         trial%r_x               , & !  1
            &         trial%r_y               , & !  2
            &   real( trial%e_x             ) , & !  3
            &   imag( trial%e_x             ) , & !  4
            &   real( trial%e_y             ) , & !  5
            &   imag( trial%e_y             ) , & !  6
            &         trial%r_op              , & !  7
            &   real( trial%e_op            ) , & !  8
            &   imag( trial%e_op            ) , & !  9
            &   real( trial%error        () ) , & ! 10
            &   imag( trial%error        () ) , & ! 11
            &   real( trial%error_scaled () ) , & ! 12
            &   imag( trial%error_scaled () )     ! 13



            if ( abs( record%error_scaled() ) .lt. abs( trial%error_scaled() ) ) then

                flag   = .true.
                record = trial
        
            end if

        end do
        end do



        if (flag) call record%display('${OPERATION}$')



        close(file_unit)



        print *, 'OK: ${OPERATION}$'

    end procedure

end submodule
