name: ci

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:

  fypp:

    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6

        with:

          python-version: '3.x'
          cache: 'pip'

      - name: Install Python dependencies

        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fypp (test)

        run: |
          cd test
          fypp -F                         unary_operator_checker.fypp  unary_operator_checker.f90
          fypp -F                         binary_operator_checker.fypp binary_operator_checker.f90
          fypp -F -DWITH_EXP              check_unary_operator.fypp    check_unary_exp.f90
          fypp -F -DWITH_LOG              check_unary_operator.fypp    check_unary_log.f90
          fypp -F -DWITH_SUB              check_binary_operator.fypp   check_binary_sub.f90
          fypp -F -DWITH_NEG              check_unary_operator.fypp    check_unary_neg.f90
          fypp -F -DWITH_ADD              check_binary_operator.fypp   check_binary_add.f90
          fypp -F -DWITH_INV              check_unary_operator.fypp    check_unary_inv.f90
          fypp -F -DWITH_MUL              check_binary_operator.fypp   check_binary_mul.f90
          fypp -F -DWITH_SQR              check_unary_operator.fypp    check_unary_sqr.f90
          fypp -F -DWITH_DIV              check_binary_operator.fypp   check_binary_div.f90
          fypp -F -DWITH_HALF             check_unary_operator.fypp    check_unary_half.f90
          fypp -F -DWITH_AVG              check_binary_operator.fypp   check_binary_avg.f90
          fypp -F -DWITH_POW              check_binary_operator.fypp   check_binary_pow.f90
          fypp -F -DWITH_SQRT             check_unary_operator.fypp    check_unary_sqrt.f90
          fypp -F -DWITH_HYPOT            check_binary_operator.fypp   check_binary_hypot.f90
          fypp -F -DWITH_LOGISTIC_SIGMOID check_unary_operator.fypp    check_unary_logistic_sigmoid.f90
          fypp -F -DWITH_COSH             check_unary_operator.fypp    check_unary_cosh.f90
          fypp -F -DWITH_SINH             check_unary_operator.fypp    check_unary_sinh.f90
          fypp -F -DWITH_TANH             check_unary_operator.fypp    check_unary_tanh.f90
          fypp -F -DWITH_COS              check_unary_operator.fypp    check_unary_cos.f90
          fypp -F -DWITH_SIN              check_unary_operator.fypp    check_unary_sin.f90
          fypp -F -DWITH_TAN              check_unary_operator.fypp    check_unary_tan.f90
          fypp -F -DWITH_ASINH            check_unary_operator.fypp    check_unary_asinh.f90
          fypp -F -DWITH_ACOSH            check_unary_operator.fypp    check_unary_acosh.f90
          fypp -F -DWITH_ACOS             check_unary_operator.fypp    check_unary_acos.f90
          fypp -F -DWITH_ATANH            check_unary_operator.fypp    check_unary_atanh.f90
          fypp -F -DWITH_ASIN             check_unary_operator.fypp    check_unary_asin.f90
          fypp -F -DWITH_ATAN             check_unary_operator.fypp    check_unary_atan.f90

      - name: Upload artifacts (test)

        uses: actions/upload-artifact@v7

        with:

          name: test-f90
          path: test/*.f90
          retention-days: 1

  test:

    needs: fypp

    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:

      matrix:

        profile: [debug, release]
      
      fail-fast: false

    steps:

      - uses: actions/checkout@v6

      - name: Download .f90 files generated by fypp (test)

        uses: actions/download-artifact@v8

        with:

          name: test-f90
          path: test

      - name: Install fpm

        uses: fortran-lang/setup-fpm@v9

        with:

          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build library using fpm

        run: fpm build --profile ${{ matrix.profile }}

      - name: Test library using fpm (${{ matrix.profile }} mode)

        run: fpm test --profile ${{ matrix.profile }}

  commit:

    needs: test

    timeout-minutes: 10

    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: |
      github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')

    steps:

      - uses: actions/checkout@v6

        with:

          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download .f90 files generated by fypp (test)

        uses: actions/download-artifact@v8

        with:
          name: test-f90
          path: test

      - name: Commit and push generated files

        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add src/*.f90
          git add test/*.f90

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate .f90 files from fypp [skip ci]"
            git push
          fi
